# An example of installing Artifactory and Xray only (disabling the rest)

### Install
# helm repo add jfrog https://charts.jfrog.io
# helm repo update
# helm upgrade --install jfp jfrog/jfrog-platform -f ./values-artifactory-xray.yaml

### Uninstall
# helm uninstall jfp
# kubectl get pvc ...
# kubectl delete pvc ...

global:
  # Generate a random join key with 'openssl rand -hex 32'
  joinKey: 00EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE123

  # Generate a random master key with 'openssl rand -hex 32'
  masterKey: 00bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb123

artifactory:
  enabled: true
  artifactory:
    # Note: For HA deployments, set replicaCount >1 (recommended 3)
    replicaCount: 1

    license:
      licenseKey: |
        cHJvZHVjdHM6CiAgYXJ0aWZhY3Rvcnk6CiAgICBwcm9kdWN0OiBaWGh3YVhKbGN6b2dNakF5TkMw
        d05TMHhNVlF3TURvd01Eb3dNRm9LYVdRNklDUTFPRGt4T0RZM0xUQm1aalV0TkRneFlTMWlaakky
        TFdJMk16RmlNakJrTXpkak9BcHZk...

  # Run every Artifactory service to its own container
  splitServicesToContainers: true

xray:
  enabled: true

# If enabling Xray, rabbitmq should also be enabled
rabbitmq:
  enabled: true

distribution:
  enabled: false

insight:
  enabled: false

pipelines:
  enabled: false

redis:
  enabled: false

pdnServer:
  enabled: false
